### PR TITLE
Boduuu coloooo

### PR DESCRIPTION
**Pull request by whmii**

### CODE REVIEW

**Comment by whmii** [comment]
@dleve123 we should probably do this on your machine since you did all the work ;)

**Comment by dleve123** [comment]
@whmii Haha, you mean to give the commits the correct author? There's actually a way to configure Git to show that some code was generated by a pair! Maybe we can try doing that.

**Comment by dleve123** [comment]
@whmii Discussing this IRL earlier today made me think about this – should we merge? I can also rebase the commits so that I'm the author if that's something we still want to do!

**Comment by whmii** [comment]
@dleve123 sounds good to me. you can also probably squash these in to a single commit

**Comment by whmii** [comment]
@dleve123 merging

**Comment by dleve123** [comment]
woo – deleting the branch for cleanliness

**Pull request merged**
